name: secret
on: 
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout secret
        env:
            secret: ${{ secrets.SECRET }}
        run: echo "The secret is \${{ secrets.SECRET }}"
          
      
